### PR TITLE
Comanage

### PR DESCRIPTION
**Pull request by muisit**

### CODE REVIEW

**Comment by baszoetekouw** [comment]
Look good in general.  Just one question: is it really necessary to install postfix?  Can't COmanage just use `/usr/bin/sendmail` (from the mail role), or connect to `{{servers.smtp_smarthost}}` instead?

**Comment by muisit** [comment]
There are several solutions probably. I took this one to avoid having to install and configure sendmail. I had a working configuration for postfix and it works almost out of the box. Also, this connects the whole server instead of just comanage, allowing other processes to send mail as well. 
In general I am not a fan of tweaking a single application to connect specifically to an external host if a more generic solution is just as easy.

**Comment by baszoetekouw** [comment]
Should be a matter of installing a custom version of `/opt/comanage/local/Config/email.php`.  We should do that anyway, to fix COmanage's `from`-address (which is set to `you@localhost` currently).

**Comment by baszoetekouw** [comment]
@muisit I'd prefer having a centealized email config, rather than having each individual application install its own email server.  The default roles already install a functional `/usr/bin/sendmail`, as well as the central email relay on `mgnt1`.  
BTW, which one of the three email configs (default, smtp, fast) is actually used by COmanage?

**Comment by muisit** [comment]
COmanage uses the 'default' email config.

**Pull request merged**
